### ISSUE TITLE
When tokens are lost

### ISSUE THREAD

**Issue by nearmax** [nearprotocol/docs#171]
We need an exhaustive documentation that describes all cases when tokens get irreversibly burnt, e.g. if transaction issues a refund receipt directed towards some beneficiary, but that beneficiary deletes the account before the refund arrives resulting in refund being lost entirely.

**Comment by nearmax** [comment]
Assigning to @amgando to create such documentation and @fckt to provide the answers.

**Comment by amgando** [comment]
@fckt and @nearmax can we start right here with a simple outline of this content?  also what does success look like?  is it a single page or something more?

**Comment by fckt** [comment]
I would need some time to go though all the possibilities.. There is a big chance to miss something.

**Comment by nearmax** [comment]
> @fckt and @nearmax can we start right here with a simple outline of this content? also what does success look like? is it a single page or something more?

I would let @fckt outline all possibilities. The success is when we know this part of the documentation is 100% exhaustive, independently on its size.

**Comment by nearmax** [comment]
@fckt please estimate how much you would need then ask @amgando how much time he would need to shape your stuff into documentation and set the "estimate" for this issue in ZenHub.

**Comment by amgando** [comment]
from @fckt 

> 1) Action::DeleteAccount and set a beneficiary_id witch doesn't exist  (such action could be genereated by a code of a smart contract as well)
> 
> 2) If account does CallFunctionAction (with an attached deposit) to one contract and that contract does CallFunctionAction to more that one contract and some of these calls fails and some are success some deposit could be stuck the contract(s) with a successful call
> 
> 3) if account deletes a last access key account don't have a contract code with logic which provide an access balance on the balance. (the same happens if user lost access to the private key attached to the assess key, obviously )

**Comment by amgando** [comment]
**for (1)** 
one question: 

- i'm surprised that we are not checking that the `beneficiary_id` exists before we delete the account in question and even locking it somehow so that it doesn't get deleted during the lifetime of applying `Action::DeleteAccount`.

**for (3)**
one question: 
- i'm surprised that we don't protect against this kind of scenario since we know how many access keys an account has and could warn / fail if this scenario is detected.

**Comment by amgando** [comment]
@fckt and @nearmax, here's where we landed for this research.  

- can i clean up and publish to docs?
- ok to publish here to Integrator docs page under FAQ ("When are tokens lost?") or would you suggest another location?

---

lost tokens are possible in multiple scenarios.  

these scenarios can be grouped into related classes:

## Type 1 Token Loss: Key Management

there is a class of token loss scenarios related to key management.  proper key management is one way to avoid this class of errors.  contract designers can also implement the logic for a contract to issue new keys which will allow for recovery of accounts whose keys have been lost or deleted.

### scenario 1.a: loss of `FullAccess` key

a user may lose their private key (`FullAccess` key) for an account which has no other keys.  no one will be able to recover the funds.  funds will remain locked in the account forever.

### scenario 1.b: loss of `FunctionCall` access key

an account may have it's one and only `FunctionCall` access key deleted.  no one will be able to recover the funds.  funds will remain locked in the account forever.


## Type 2 Token Loss: Refunds

there is a class of token loss scenarios related to refund receipts.  when a receipt is issued for an account, if that account no longer exists, the funds will be dispersed among validators proportional to their stake in the current epoch.

### scenario 2.a: delete account with non-existent beneficiary

for an account to be deleted, a beneficiary must be assigned.  once deleted, a transfer receipt is generated and sent to the beneficiary account.  if the beneficiary account does not exist, a refund receipt will be generated and sent back to the original account.  since the original account has already been deleted, the funds will be dispersed among validators

### scenario 2.b: account with zero balance receives refund

if an account `A` transfers all of its funds to another account `B` and account `B` does not exist, a refund receipt will be generated for account `A`.  during the period of this round trip, account `A` is vulnerable to deletion by garbage collection activities on the network. if account `A` is in fact deleted before the refund receipt arrives, then the funds will be dispersed among validators.

## Type 3 Token Loss: Function Calls

there is a class of token loss scenarios related to the failure of function calls.

### scenario 3.a: successful calls in a failed batch

if a contract function `f1` calls two or more other functions `f2` and `f3`, and at least one of these functions `f2` and `f3` fails, then tokens will be returned from function(s) which fail but tokens will be lost to the function(s) which succeed.

**Comment by fckt** [comment]
> scenario 1.b: loss of FunctionCall access key
an account may have it's one and only FunctionCall access key deleted. no one will be able to recover the funds. funds will remain locked in the account forever.

FunctionCall access key by itself don't give a direct access for spending, so we can omit this case IMO

**Comment by amgando** [comment]
i thought under `scenario 1.b` it was the case that a contract, which was originally designed to control funds for an account, has a FunctionCall access key which is deleted.  in this scenario, the contract would lose the ability to control funds so it fits the model, right?

**Comment by amgando** [comment]
added to integrator path here: `/docs/roles/integrator/token-loss`

![image](https://user-images.githubusercontent.com/24913/74026099-72f8b980-49b6-11ea-9a24-f2b3460ec110.png)
