### ISSUE TITLE
PyNear docs deprecated update to Near Shell

### ISSUE THREAD

**Issue by ckshei** [nearprotocol/docs#36]
Pynear is broken and deprecated. We should remove it from the documentation + update it with Near Shell once it's been updated with full functionality

**Comment by nearmax** [comment]
The problem is that Near Shell does not fully supersede Pynear. Pynear is basically a wrapper around our node RPC, while Near Shell has a subset of commands. CC @potatodepaulo

**Comment by vgrichina** [comment]
@nearmax which commands are currently missing that were present in pynear? It generally is pretty easy to add new commands, I'd like to just do a single pass to complete puzzle.

**Comment by nearmax** [comment]
- [ ] send_money
- [ ] view_account
- [ ] view_state
- [ ] stake (this will be more complex, because people will be able to stake in several different ways: as validators and verifiers)
- [ ] swap_key
- [ ] view latest block
- [ ] get block by hash

Note, there is also other stuff that was not in pynear but we will very likely have:
- [ ] expiration_date  Returns date and time of contract or access key expiration due to rent payments;
- [ ] add_access_key
- [ ] delete_access_key
- [ ] delete_account (Both delete_access_key and delete_account can be called by non-account owner if they are about to run out of balance due to rent)
- [ ] async_call (for contract calls the incur a long chain of cross-contract calls)
- [ ] async_status

Note, that some of these functions are or will be special cases of more generic functions. For instance, we discussed with @evgenykuzyakov and @ilblackdragon that we want all our transactions to look like function calls for consistency and forward compatibility. For instance, send_money will be a short cut for near call <my_account> send_money "{\"receiver\": <other_account>}", or somesuch.

**Comment by potatodepaulo** [comment]
near-shell now full-featured.
